### ISSUE TITLE
Question about result evaluation

### ISSUE THREAD

**Issue by light8lee** [fenchri/edge-oriented-graph#11]
why the gold data you generated in CDR dataset contains `1:NR:2`? I think it should only consider about `1:CID:2` type.
For example, you generated follow lines as gold data
```
8701013|D015738|D003693|NON-CROSS|1:CID:2
8701013|D015738|D014456|NON-CROSS|1:NR:2
439781|D007213|D007022|NON-CROSS|1:CID:2
439781|D012964|D007022|NON-CROSS|1:NR:2
439781|D011453|D007022|CROSS|1:NR:2
439781|D000809|D007022|CROSS|1:NR:2
```
why not
```
8701013|D015738|D003693|NON-CROSS|1:CID:2
439781|D007213|D007022|NON-CROSS|1:CID:2
```

**Comment by fenchri** [comment]
During evaluation I consider only the positive pairs, but I generated this for some analysis I did.
If you check the _evaluation.py_ script you will see that the NR pairs are actually skipped.

BTW, the script works for binary classification problems, I will make it generalisable soon.

**Comment by light8lee** [comment]
OK, I find that part, you are right.
