### ISSUE TITLE
something wrong with "genia-tagger-py"

### ISSUE THREAD

**Issue by yangxia605** [fenchri/edge-oriented-graph#14]
hello,fenia when i run "cd genia-tagger-py && make",something wrong as follows:
![image](https://user-images.githubusercontent.com/21167278/75316099-5fe35600-589f-11ea-9a30-8caece7c33c9.png)
can you help me?thank you  sooooo much!

**Comment by fenchri** [comment]
Hi there,

Yeah there is an issue with the website and we transferred Genia Tagger into a new address. The genia-tagger-py repo has the old version.

What you can do now, is to simply edit the Makefile inside genia-tagger-py.
Simply replace line 3 [here](https://github.com/bornabesic/genia-tagger-py/blob/master/Makefile) with this one: `wget http://www.nactem.ac.uk/GENIA/tagger/geniatagger-3.0.2.tar.gz`

Re-run make again after that.
Hope this helps!

**Comment by yangxia605** [comment]
thank you.i got it!
