### ISSUE TITLE
confused about the graph structure?

### ISSUE THREAD

**Issue by yangxia605** [fenchri/edge-oriented-graph#15]
@fenchri 
hi fenchri:
i am curious about the graph in this paper,is it an ordinary graph just as a data structure.and diffirent from gnn/gcn?because the words embedding is learning from glove or pretrained but not node2vec?
hope you can see what i say.
thanks!

**Comment by fenchri** [comment]
Hi, 

The graph is heterogeneous meaning that we have different types of nodes (entity, mention, sentence).
The nodes are connected in pairs and for each pair we create an embedding (edge embedding - this is different from GCN that learns node embeddings).

Pre-trained word embeddings are used, but the node and edge embeddings are created using information from the text (I don't use node2vec which is different).
To clarify, the graph connections, node and edge embeddings are created given a text document as input, using the heuristics described in the paper.

I am not sure I get 100% what you mean, but I hope I answered your question.

**Comment by yangxia605** [comment]
thanks for your explaination.I get it and read the another relative paper "Inter-sentence Relation Extraction with Document-level Graph Convolutional Neural Network".
