### ISSUE TITLE
Question about train error

### ISSUE THREAD

**Issue by ssppff** [fenchri/edge-oriented-graph#17]
Hello,dear fenchri.when Irun this comman:
python3 eog.py --config ../configs/parameters_cdr.yaml --train --gpu -0 --early_stop

something wrong as follows:
![image](https://user-images.githubusercontent.com/48555357/77502658-6a8d0d00-6e96-11ea-85bb-09abf1337eef.png)

**Comment by fenchri** [comment]
Hey there,

I suspect you are trying to run the reproduce version? Could you provide the walks length as well?
For instance:
``` python3 eog.py --config ../configs/parameters_cdr.yaml --train --gpu -0 --early_stop --walks 3 ```
If you don't want to use walks, just type ```--walks 0```.

This will solve it for you :)

**Comment by ssppff** [comment]
Thank you. I didn't think about the step length in training. Now I understand.
