### ISSUE TITLE
a question about processed trained.data.

### ISSUE THREAD

**Issue by yangxia605** [fenchri/edge-oriented-graph#18]
@fenchri 
There still has a quesion with me when generate processed trained.data form processed traning.pubtator
Cay you share me an exapmle about what processed trained.data looks like.just show me a pid of trained.data. 
thanks !!!

**Comment by fenchri** [comment]
Hi,

Are you not able to generate the *.data file? The general format is as follows:

```PID<tab>tokenized_sentences_separated_by_|<tab>relation<tab>direction<tab>cross/non-cross<tab>closest_arg1_start-closest_arg1_end<tab>closest_arg2_start-closest_arg2_end<tab>arg1_KB_id<tab>mentions_for_arg1_separated_by_|<tab>arg1_type<tab>start_token_ids_arg1_separated_by_:<tab>end_token_ids_arg1_separated_by_:<tab>sentence_ids_separated_by_:<tab>arg2_KB_id<tab>mentions_for_arg2_separated_by_|<tab>arg2_type<tab>start_token_ids_arg2_separated_by_:<tab>end_token_ids_arg2_separated_by_:<tab>sentence_ids_separated_by_:```

The same line continues for all the pairs in the document. A new line contains another document. Is that helpful?

**Comment by yangxia605** [comment]
yes.that's great.thank you so much.you are so kind.
