### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'path_to_predictions_file'

### ISSUE THREAD

**Issue by ssppff** [fenchri/edge-oriented-graph#19]
Hello, fenchri.when Irun this comman:
python3 evaluate.py --pred path_to_predictions_file --gold ../data/CDR/processed/test.gold --label 1:CDR:2
I found that I couldn't find the file "path_to_predictions_file" ,but when I created the discovery in the ** **evaluation** file, the results were all 0. I hope you can help me

**Comment by fenchri** [comment]
Hi,

Did you run the model first? After you run the model, you can find the predictions in the repository that will be created.
Then you can run the following, by replacing the "named_of_experiment" with the name of the experiment you want to evaluate. This can be found in the `results` folder:
```python3 evaluate.py --pred ../results/name_of_experiment/test.preds / --fold ../data/CDR/processed/test_filter.gold --label 1:CDR:2```

**Comment by ssppff** [comment]
Hello, I ran the model according to the method, but in the **results** file, there is only the **dev.preds** file, and no **test.preds** is generated.

**Comment by fenchri** [comment]
Please check the config file. The model is trained and evaluated on the files that are specified there. 
The evaluation script can be used to evaluate either dev or test data, just change the input.
Also, please note the you need to use the train_filter.data, dev_filter.data and test_filter.data for the CDR dataset.

**Comment by ssppff** [comment]
OK, I think I understand, thank you for your help.
