### ISSUE TITLE
Where does 'PubMed-CDR.txt' come from?

### ISSUE THREAD

**Issue by dawn2034** [fenchri/edge-oriented-graph#2]
Dear Fenia,
I meet an error when run the function 'load_embeds' in 'loader.py'.
> FileNotFoundError: [Errno 2] No such file or directory: '../embeds/PubMed-CDR.txt'

I didn't find the missing file in the folder embeds/ and in 'bio_nlp_vec.tar.gz'. Where does 'PubMed-CDR.txt' come from?

**Comment by fenchri** [comment]
Hi, sorry about that. 
There is a script missing for reducing the number of embeddings from PubMed based on the words contained in the CDR corpus. I will add this around Friday. 
You can change the file to the full PubMed embeddings for now and use the code if you want :) Just decompress the embeddings file first!

**Comment by dawn2034** [comment]
> Hi, sorry about that.
> There is a script missing for reducing the number of embeddings from PubMed based on the words contained in the CDR corpus. I will add this around Friday.
> You can change the file to the full PubMed embeddings for now and use the code if you want :) Just decompress the embeddings file first!

Thank you. I load the full PubMed embeddings successfully with gensim package. 
I also meet some errors:
1) Two sh commands in README.md:
    > $ sh process_cdr.sh
    > $ sh process_cdr.sh

    One of them should be '$ sh process_gda.sh'

2) The the missing of hyperpatameter 'walks_iter' in parameters_cdr.yaml:
https://github.com/fenchri/edge-oriented-graph/blob/56d9e4f604f7d062c897513c6e09f566869ca22a/configs/parameters_cdr.yaml#L21
It will raise a TypeError when I run "$ python3 eog.py --config ../configs/parameters_cdr.yaml --train --gpu 0":
https://github.com/fenchri/edge-oriented-graph/blob/56d9e4f604f7d062c897513c6e09f566869ca22a/src/nnet/init_net.py#L80

3) And values of hyperpatameters 'tune_bias', 'window' in parameters_cdr.yaml are also missing. I don't know if they will cause any errors.

4) The path in test_data is 'processed' instead of 'procesed': 
https://github.com/fenchri/edge-oriented-graph/blob/56d9e4f604f7d062c897513c6e09f566869ca22a/configs/parameters_cdr.yaml#L26

Thank you for correcting these issues! : )

**Comment by fenchri** [comment]
Thanks for pointing these out! I will update this thread as soon as I upload the corrected version. 
Again apologies for both the delay and the issues :)

**Comment by fenchri** [comment]
Ok, I think everything should be ok now. Please close this issue if that fixes it for you :)
