### ISSUE TITLE
question about datasets statistics 

### ISSUE THREAD

**Issue by light8lee** [fenchri/edge-oriented-graph#20]
In your paper, the number of negative pairs of train, dev and test are 4202, 4075 and 4138, however, the `statistics.py` gives me `1572(intra)+2822(inter)=4394`, `1709+2540=4249`, `1656+2683=4339`, could you please tell me where may the difference come from?

**Comment by fenchri** [comment]
Hi,

Sorry about that, you should use the `*_filter.data` when counting the statistics (for the CDR dataset). The `*.data` files contain non-filtered data including hypernyms.
I will correct this in the description!

**Comment by light8lee** [comment]
OK, I got the correct statistics.
