### ISSUE TITLE
Some questions about  intra-sentences or inter-sentences

### ISSUE THREAD

**Issue by wenzitracyliu** [fenchri/edge-oriented-graph#22]
Hello, I used your model to run on the document, but I don't know how to get the results of intra-sentence classification or inter-sentence classification. Could you tell me how to do that? Do you use intra-sentences to train your model and only test on the intra-sentence?

**Comment by fenchri** [comment]
Hi, thanks for your interest in the model!

The model is trained simultaneously on both intra- and inter-sentence pairs. An inter-sentence pair is defined when there is no mention of this pair in the same sentence. I have an [evaluation script](https://github.com/fenchri/edge-oriented-graph/blob/master/evaluation/evaluate.py) that can be used to report the performance on intra- and inter-sentence pairs separately. 
There is information about how to use it in the README.
Was this what you needed?

**Comment by wenzitracyliu** [comment]
Thanks, I see.
