### ISSUE TITLE
Error in Data Processing

### ISSUE THREAD

**Issue by amirveyseh** [fenchri/edge-oriented-graph#23]
In data processing, after runing `sh process_cdr.sh`, I got this error: 'FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt''

The full error is:

`11923it [00:00, 45980.01it/s]
Processing Doc_ID 227508:   0%|                                                                                                               | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "process.py", line 123, in <module>
    main()
  File "process.py", line 62, in main
    split_sents = sentence_split_genia(orig_sentences)
  File "/disk/apouranb/RAMS/RAMS/classification_code/OT/EoG/edge-oriented-graph/data_processing/tools.py", line 248, in sentence_split_genia
    with open('temp_file.split.txt', 'r') as ifile:
FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt'
Loading examples from ../data/CDR/processed/Training.data
Mesh entities: 28470
Positive Docs: 0
Negative Docs: 0
Positive Count: 0   Initial Negative Count: 0   Final Negative Count: 0   Hyponyms: 0
0
12103it [00:00, 45581.38it/s]
Processing Doc_ID 6794356:   0%|                                                                                                              | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "process.py", line 123, in <module>
    main()
  File "process.py", line 62, in main
    split_sents = sentence_split_genia(orig_sentences)
  File "/disk/apouranb/RAMS/RAMS/classification_code/OT/EoG/edge-oriented-graph/data_processing/tools.py", line 248, in sentence_split_genia
    with open('temp_file.split.txt', 'r') as ifile:
FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt'
Loading examples from ../data/CDR/processed/Development.data
Mesh entities: 28470
Positive Docs: 0
Negative Docs: 0
Positive Count: 0   Initial Negative Count: 0   Final Negative Count: 0   Hyponyms: 0
0
`

**Comment by fenchri** [comment]
Hi,

Did you install geniass correctly along with the requirements? 
I re-ran the process and I don't see the error appearing.
Could you remove the processed folder and try again?

**Comment by amirveyseh** [comment]
Thanks, I re-installed geniass and it worked.
