### ISSUE TITLE
some issues of code for Pre-processing

### ISSUE THREAD

**Issue by njcx-ai** [fenchri/edge-oriented-graph#24]
When i run the script sh process_cdr.sh in Datasets & Pre-processing module, i have failed.
   I have found this line 'os.system('./geniass temp_file.txt temp_file.split.txt > /dev/null 2>&1')'  report an error. The error screenshot is shown below.  Does the code of data processing need ruby??  My linux system don't install ruby, and it is troubled to install it .
![1608713963(1)](https://user-images.githubusercontent.com/60687114/102980057-ead5c100-4541-11eb-909f-6295e0e1e977.png)

**Comment by seanswyi** [comment]
You need to install Ruby. It's not really that troublesome to install it... All you have to do is run `sudo apt-get install ruby-full`.

**Comment by Amadeus-JD** [comment]
I also got an error while use the script process_cdr,sh..... it is 
![微信截图_20210326125440](https://user-images.githubusercontent.com/49356096/112584407-c0dab600-8e32-11eb-8cef-466dfe4d9852.jpg)

I think it can't read the temp file.... but I never change the code ....

**Comment by seanswyi** [comment]
@ChristopherAmadeusMiao Did you install Ruby? Make sure Ruby's installed and run the code again.

**Comment by Amadeus-JD** [comment]
> @ChristopherAmadeusMiao Did you install Ruby? Make sure Ruby's installed and run the code again.

。。。you are right....I solved it... .just reinstall the ruby.  thank you

**Comment by fenchri** [comment]
Apologies for the late reply everyone! Indeed ruby needs to be installed for this to work. I will add it in the requirements files since many seem to have the same issue!

Thanks again for your interest!
