### ISSUE TITLE
data process and geniass install problem

### ISSUE THREAD

**Issue by Amadeus-JD** [fenchri/edge-oriented-graph#25]
I also got an error while use the script process_cdr,sh..... it is 
![微信截图_20210326125440](https://user-images.githubusercontent.com/49356096/112584407-c0dab600-8e32-11eb-8cef-466dfe4d9852.jpg)

I think it can't read the temp file.... but I never change the code ....

_Originally posted by @miaodatiancai in https://github.com/fenchri/edge-oriented-graph/issues/24#issuecomment-807935345_

**Comment by Amadeus-JD** [comment]
and when I try to  reinstall the geniass ...it comes so much warning.... is it something to do with the error?
![geniass2](https://user-images.githubusercontent.com/49356096/112586160-38f6ab00-8e36-11eb-89bc-897d5a33bdb8.jpg)

**Comment by Amadeus-JD** [comment]
sry....i sovled this issue ....
nothing to do with that install
just install the ruby... that could solve

**Comment by fenchri** [comment]
#24
