### ISSUE TITLE
some questions about the processed data

### ISSUE THREAD

**Issue by Amadeus-JD** [fenchri/edge-oriented-graph#26]
PID<tab>tokenized_sentences_separated_by_|<tab>relation<tab>direction<tab>cross/non-cross<tab>closest_arg1_start-closest_arg1_end<tab>closest_arg2_start-closest_arg2_end<tab>arg1_KB_id<tab>mentions_for_arg1_separated_by_|<tab>arg1_type<tab>start_token_ids_arg1_separated_by_:<tab>end_token_ids_arg1_separated_by_:<tab>sentence_ids_separated_by_:<tab>arg2_KB_id<tab>mentions_for_arg2_separated_by_|<tab>arg2_type<tab>start_token_ids_arg2_separated_by_:<tab>end_token_ids_arg2_separated_by_:<tab>sentence_ids_separated_by_:

I saw this is the processed data format.... 
i want to ask what is direction mean??

why 

                    if p[1] == "L2R":
                        h_id, t_id = p[5], p[11]
                        h_start, t_start = p[8], p[14]
                        h_end, t_end = p[9], p[15]
                    else:
                        t_id, h_id = p[5], p[11]
                        t_start, h_start = p[8], p[14]
                        t_end, h_end = p[9], p[15]

what is L2R and R2L  why have to change the position of head entity and tail entity??

**Comment by fenchri** [comment]
Hello,

L2R and R2L simply indicate the order to the entities in the sentence, which one appears first and which one appears second (left-to-right and right-to-left). 
It doesn't play much role in CDR and GDA because we want interactions between specific entity types. But generally, the order of the entities influences the direction of the relation (from the 1st entity to the 2nd or from the 2nd to the 1st).

**Comment by Amadeus-JD** [comment]
> Hello,
> 
> L2R and R2L simply indicate the order to the entities in the sentence, which one appears first and which one appears second (left-to-right and right-to-left).
> It doesn't play much role in CDR and GDA because we want interactions between specific entity types. But generally, the order of the entities influences the direction of the relation (from the 1st entity to the 2nd or from the 2nd to the 1st).

thank you so much...  . 
I want to make sure that the head entity is Chemical and tail entity is Disease...
Could I just change this Module。。（with do not judge the p[1]'s value....)  to achieve this goal?

**Comment by fenchri** [comment]
The model makes sure that it classifies the pair with head entity Chemical and tail Disease, you don't need to change anything in the script.

**Comment by Amadeus-JD** [comment]
> The model makes sure that it classifies the pair with head entity Chemical and tail Disease, you don't need to change anything in the script.

OK.....thank you so much
