### ISSUE TITLE
how to understand the processed data

### ISSUE THREAD

**Issue by yyzhuang1991** [fenchri/edge-oriented-graph#28]
I am a bit confused about the representation of processed_data. 

     PID<tab>tokenized_sentences_separated_by_|<tab>relation<tab>direction<tab>cross/non-cross<tab>closest_arg1_start-closest_arg1_end<tab>closest_arg2_start-closest_arg2_end<tab>arg1_KB_id<tab>mentions_for_arg1_separated_by_|<tab>arg1_type<tab>start_token_ids_arg1_separated_by_:<tab>end_token_ids_arg1_separated_by_:<tab>sentence_ids_separated_by_:<tab>arg2_KB_id<tab>mentions_for_arg2_separated_by_|<tab>arg2_type<tab>start_token_ids_arg2_separated_by_:<tab>end_token_ids_arg2_separated_by_:<tab>sentence_ids_separated_by_:

For example, the following text is the third segment of the first line in train_filter.data: 
    
    1:CID:2	R2L	NON-CROSS	58-61	51-52	D008750	alpha - methyldopa|alpha - methyldopa	Chemical	58:203	61:206	2:6	D007022	hypotensive	Disease	51	52	2
which i think means there is a CID relation, in the concept level,  between the entities D008750 and D007022. D008750 has two mentions at (58, 61) and (203,206), while D007022 has only 1 mention at (51,52). Is this correct? 

And what does the non-cross mean here, cause it does have a relation across sentences (e.g. mention 2 of D008750 is in sentence 6 and while  D007022 is in sentence 2) ? Is it specifically used for the relation between the closest mention pair?

**Comment by fenchri** [comment]
Hello,

Yes, your understanding is correct!

The "non-cross" means that this concept pair is not inter-sentential. We used this to evaluate intra- and inter-sentence pairs separately. If there is at least a mention pair in the same sentence, then the concept-level pair is considered non-cross. 
In order for a pair to be "cross", there should be no mentions of it in the same sentence. 

If you see, one mention of the Disease is found in sentence 2 and one mention of the Chemical is also in sentence 2. So the pair is ultimately intra-sentential.

Hope that helps!

**Comment by yyzhuang1991** [comment]
I see. Thank you!
