### ISSUE TITLE
filter_hypernyms.py

### ISSUE THREAD

**Issue by ZhangYi0621** [fenchri/edge-oriented-graph#29]
Hello!
Thanks for  your excellent work~
I have a question about filter hyponys. 
filter_hypernyms.py
#102   ne[0] = 'not_include'   # just don't include the negative pairs, but keep the entities

Why  should we  do this step~
Looking forward to your reply！

**Comment by fenchri** [comment]
Hello and thanks for your message!

We filter hypernyms following prior work. 

However, the approach constructs a graph with entities as nodes, hence all entities in a document are important in the graph. As a result, we keep them but do not classify those entity pairs as prior work ignored them.

**Comment by ZhangYi0621** [comment]
> 

ok!  I see~ 
Thanks for your reply! I have found the original paper of filtering hypernyms.

**Comment by ZhangYi0621** [comment]
您好，来信已收到，祝好！
