### ISSUE TITLE
help

### ISSUE THREAD

**Issue by chengzhenq** [fenchri/edge-oriented-graph#30]
when I run sh process_cdr.sh
The following problems occurred:
czr@DESKTOP-QR7Q65P MINGW64 /d/edge-oriented-graph-reproduceEMNLP/data_processing
$ sh process_cdr.sh
mv: cannot stat '../data/CDR/processed/Training.data': No such file or directory
mv: cannot stat '../data/CDR/processed/Development.data': No such file or directory
mv: cannot stat '../data/CDR/processed/Test.data': No such file or directory
mv: cannot stat '../data/CDR/processed/Training_filter.data': No such file or directory
mv: cannot stat '../data/CDR/processed/Development_filter.data': No such file or directory
mv: cannot stat '../data/CDR/processed/Test_filter.data': No such file or directory
cat: ../data/CDR/processed/train_filter.data: No such file or directory
cat: ../data/CDR/processed/dev_filter.data: No such file or directory
<img width="450" alt="捕获" src="https://user-images.githubusercontent.com/91397647/158302525-0a91616e-dffa-4208-bdfc-85be6e66eb23.PNG">

**Comment by fenchri** [comment]
Hello, could you check previous issues for this? I think the tokenizer wasn't run properly, so might need to check what happened there.

**Comment by WilliamAntoniocrayon** [comment]
> when I run sh process_cdr.sh The following problems occurred: czr@DESKTOP-QR7Q65P MINGW64 /d/edge-oriented-graph-reproduceEMNLP/data_processing $ sh process_cdr.sh mv: cannot stat '../data/CDR/processed/Training.data': No such file or directory mv: cannot stat '../data/CDR/processed/Development.data': No such file or directory mv: cannot stat '../data/CDR/processed/Test.data': No such file or directory mv: cannot stat '../data/CDR/processed/Training_filter.data': No such file or directory mv: cannot stat '../data/CDR/processed/Development_filter.data': No such file or directory mv: cannot stat '../data/CDR/processed/Test_filter.data': No such file or directory cat: ../data/CDR/processed/train_filter.data: No such file or directory cat: ../data/CDR/processed/dev_filter.data: No such file or directory <img alt="捕获" width="450" src="https://user-images.githubusercontent.com/91397647/158302525-0a91616e-dffa-4208-bdfc-85be6e66eb23.PNG">

hi，bro！Are you get over this problem?

**Comment by suexin27** [comment]
hi，when I run sh process_gda.sh, The following problems occurred:
FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt'

**Comment by Kakarot-Li** [comment]
sorry to disturb , I didn't have the file named 'temp_file.split.txt' ，if you have this file ,would you please help me out? thanks a lot

**Comment by fenchri** [comment]
Hello, please make sure `ruby` is installed. Do a fresh install of the packages and try again? In case you are running this on Windows, I am not sure I can help as this code was tested only on Ubuntu.

Thank you

**Comment by Kakarot-Li** [comment]
> Hello, please make sure `ruby` is installed. Do a fresh install of the packages and try again? In case you are running this on Windows, I am not sure I can help as this code was tested only on Ubuntu.
> 
> Thank you

it works! appreciate
