### ISSUE TITLE
Hi, I got a problem about:AttributeError: 'GeniaTagger' object has no attribute 'tag'

### ISSUE THREAD

**Issue by WilliamAntoniocrayon** [fenchri/edge-oriented-graph#34]
![image](https://user-images.githubusercontent.com/40733610/177950552-62f9055a-3b9f-4bf7-816d-674ee9bfd342.png)

I'm curious about the reason for this mistake.

**Comment by fenchri** [comment]
Hi, have you installed GeniaTagger as described in the readme?

**Comment by WilliamAntoniocrayon** [comment]
> 您好，您是否按照自述文件中的说明安装了 GeniaTagger？

Yes, I have installed geniatagger as required.

**Comment by Kakarot-Li** [comment]
sorry to disturb , I didn't have the file named 'temp_file.split.txt' ，if you have this file ,would you please help me out? thanks a lot

**Comment by zzhinlp** [comment]
How did you solve it?
'GeniaTagger' object has no attribute 'tag'
