### ISSUE TITLE
geniatagger File not Found Error

### ISSUE THREAD

**Issue by Polarisjame** [fenchri/edge-oriented-graph#36]
This happens when I run process.py to process CDRdata:
```
Traceback (most recent call last):
  File "process.py", line 17, in <module>
    from tools import sentence_split_genia, tokenize_genia
  File "E:\TOOL\pythonProgram\edge-oriented-graph-master\data_processing\tools.py", line 25, in <module>
    genia_tagger = GENIATagger(os.path.join("./common", "genia-tagger-py", "geniatagger-3.0.2", "geniatagger"))
  File "./common/genia-tagger-py\geniatagger.py", line 34, in __init__
    cwd = directory
  File "E:\TOOL\Annaconda\envs\pycharm\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "E:\TOOL\Annaconda\envs\pycharm\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by Kakarot-Li** [comment]
sorry to disturb , I didn't have the file named 'temp_file.split.txt' ，if you have this file ,would you please help me out? Much thanks a lot

**Comment by Kakarot-Li** [comment]
sorry to disturb , I didn't have the file named 'temp_file.split.txt' ，if you have this file ,would you please help me out? thanks a lot

**Comment by Polarisjame** [comment]
> sorry to disturb , I didn't have the file named 'temp_file.split.txt' ，if you have this file ,would you please help me out? thanks a lot

Sorry, I don't have this file either:sob:, and I can't actually run the code successfully yet

**Comment by Kakarot-Li** [comment]
damn ...

**Comment by Kakarot-Li** [comment]
> > sorry to disturb , I didn't have the file named 'temp_file.split.txt' ，if you have this file ,would you please help me out? thanks a lot
> 
> Sorry, I don't have this file either😭, and I can't actually run the code successfully yet

damn...

**Comment by Kakarot-Li** [comment]
> > sorry to disturb , I didn't have the file named 'temp_file.split.txt' ，if you have this file ,would you please help me out? thanks a lot
> 
> Sorry, I don't have this file either😭, and I can't actually run the code successfully yet

i figured it out ! apt-get install ruby-full is necessary
