### ISSUE TITLE
a strange problem

### ISSUE THREAD

**Issue by Kakarot-Li** [fenchri/edge-oriented-graph#37]
sorry to disturb ! I was stuck at the step 
<sh process_cdr.sh > and <process_gda.sh>,
it reminds me that 
<FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt'>
I have no idea what to do with this 'temp_file.split.txt'

**Comment by zzhinlp** [comment]
I can't download geniass-1.00.tar.gz, can you send a copy please?
email：zhangzhi@nudt.edu.cn
Thank you very much!

**Comment by Kakarot-Li** [comment]
不好意思 我也没有下载成功。。











在 2023-06-28 20:05:35，"zzhinlp" ***@***.***> 写道：

I can't download geniass-1.00.tar.gz, can you send a copy please?
***@***.***
Thank you very much!
