### ISSUE TITLE
something wrong with me.

### ISSUE THREAD

**Issue by yangxia605** [fenchri/edge-oriented-graph#4]
when I run : cd genia-tagger-py && make
the error :
![image](https://user-images.githubusercontent.com/21167278/68584758-72d24600-04bb-11ea-8374-90ab4aff4fb3.png)
thanks!

**Comment by fenchri** [comment]
Looks like the original file is corrupt. Maybe try to download it again?
I haven't encountered this error before.

**Comment by yangxia605** [comment]
thanks, I'll try it right away.
