### ISSUE TITLE
training error 

### ISSUE THREAD

**Issue by yangxia605** [fenchri/edge-oriented-graph#6]
hello,dear fenchri.when i run this comman:
python3 eog.py --config ../configs/parameters_cdr.yaml --train --gpu -1  --early_stop

something wrong as follows:

![image](https://user-images.githubusercontent.com/21167278/69703929-6d1c6780-112d-11ea-8a71-c8ca93931bbb.png)

Thank you so so so much!

**Comment by yangxia605** [comment]
TypeError: repeat(): argument 'repeats' (position 1) must be tuple of ints, not Tensor

**Comment by light8lee** [comment]
same with you

**Comment by fenchri** [comment]
Many thanks for catching this! 
I fixed it now, so please pull the latest version and try again!
Let me know if everything is ok :)

**Comment by yangxia605** [comment]
Thanks to your efforts, the code now works fine.By the way,I wonder if this model can be applied to the pre-trained BioBERT language model?Thank you again :)

**Comment by fenchri** [comment]
Sure, if you want you can simply change the encoder and use BERT in its place.  :)

**Comment by yangxia605** [comment]
thanks :)
